-- drop table if exists keypoints_config;
create table if not exists keypoints_config( id int NOT NULL,
                                    key_name text NOT NULL,
                                    updated_at TIMESTAMP DEFAULT(DATETIME('now','localtime')),
                                    PRIMARY KEY(id)
                                );
drop table if exists frame_info;
create table if not exists frame_info( case_name text NOT NULL,
                                    img_path text,
                                    fps real NOT NULL,
                                    height int NOT NULL,
                                    width int NOT NULL,
                                    import int DEFAULT(0),
                                    start_frame int DEFAULT(0),
                                    stop_frame int DEFAULT(0),
                                    csv_path text,
                                    memo text DEFAULT(''),
                                    updated_at TIMESTAMP DEFAULT(DATETIME('now','localtime')),
                                    inserted_at TIMESTAMP DEFAULT(DATETIME('now','localtime')),
                                    PRIMARY KEY(case_name)
                                );
--drop table if exists act_param;
create table if not exists act_param( frame int  NOT NULL,
                                    lag int default(0),
                                    model text NOT NULL,
                                    step int NOT NULL,
                                    act int NOT NULL,
                                    sect int NOT NULL,
                                    idx int NOT NULL,
                                    val real NOT NULL,
                                    inserted_at TIMESTAMP DEFAULT(DATETIME('now','localtime')),
                                    PRIMARY KEY(frame, lag, model, step, act, sect, idx)
                                );
--drop table if exists tracking_data;
create table if not exists tracking_data( case_name text NOT NULL,
                                    frame_no int NOT NULL,
                                    key_id int NOT NULL,
                                    key_name text NOT NULL,
                                    box_id int NOT NULL,
                                    box_w real NOT NULL,
                                    box_h real NOT NULL,
                                    x real NOT NULL,
                                    y real NOT NULL,
                                    xy_conf real NOT NULL, 
                                    norm real NOT NULL,
                                    ratio real NOT NULL,
                                    angle real NOT NULL, 
                                    inserted_at TIMESTAMP DEFAULT(DATETIME('now','localtime')),
                                    time_epoch integer,
                                    PRIMARY KEY(case_name, frame_no, key_id)
                                );
--drop table if exists kyudo_data;
create table if not exists kyudo_data( case_name text NOT NULL,
                                    frame_no int NOT NULL,
                                    box_id int NOT NULL,
                                    box_conf real NOT NULL, 
                                    box_w real NOT NULL,
                                    box_h real NOT NULL,
                                    rw_norm real DEFAULT(0.0),
                                    rw_angle real DEFAULT(0.0), 
                                    lw_norm real DEFAULT(0.0),
                                    lw_angle real DEFAULT(0.0), 
                                    rl_norm real DEFAULT(0.0), 
                                    rl_angle real DEFAULT(0.0), 
                                    hr_norm real DEFAULT(0.0), 
                                    hr_angle real DEFAULT(0.0), 
                                    sr_norm real DEFAULT(0.0), 
                                    sr_angle real DEFAULT(0.0), 
                                    sl_norm real DEFAULT(0.0), 
                                    sl_angle real DEFAULT(0.0), 
                                    rew_angle real DEFAULT(0.0), 
                                    rse_angle real DEFAULT(0.0), 
                                    lew_angle real DEFAULT(0.0), 
                                    lse_angle real DEFAULT(0.0), 
                                    eyes_norm real DEFAULT(0.0), 
                                    hips_norm real DEFAULT(0.0), 
                                    section int DEFAULT(0),
                                    completed int DEFAULT(0),
                                    tag1 int DEFAULT(NULL),
                                    tag2 int DEFAULT(NULL),                               
                                    label int DEFAULT(0),
                                    inserted_at TIMESTAMP DEFAULT(DATETIME('now','localtime')),
                                    time_epoch integer,
                                    PRIMARY KEY(case_name, frame_no) 
                                );
--drop table if exists eval_data;
create table if not exists eval_data( case_name text NOT NULL,
                                    lv int NOT NULL,
                                    frame_no int NOT NULL,
                                    section int NOT NULL,
                                    completed int NOT NULL,
                                    step int NOT NULL,
                                    score int DEFAULT(0),
                                    split real DEFAULT(0.0),
                                    rl real DEFAULT(0.0),
                                    er real DEFAULT(0.0),
                                    sl real DEFAULT(0.0),
                                    push int DEFAULT(0),
                                    pull int DEFAULT(0),
                                    alart int DEFAULT(0),
                                    inserted_at TIMESTAMP DEFAULT(DATETIME('now','localtime')),
                                    time_epoch integer,
                                    PRIMARY KEY(case_name, frame_no, time_epoch)
                                );
